language: go

go:
  - "1.10.x"
  
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_b0ccc0a83fd8_key 
    -iv $encrypted_b0ccc0a83fd8_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - go get -u github.com/Masterminds/glide

install:
  - glide install
  
script:
  - go build -o bin
  - tar -zcvf sorry-gen.tar.gz ./bin ./resources
deploy:
  provider: releases
  file: sorry-gen.tar.gz
  skip_cleanup: true
