language: go

go:
  - "1.10.x"
  
before_install:
  - go get -u github.com/Masterminds/glide

install:
  - glide install
  
script:
  - go build -o bin
  - tar -zcvf sorry-gen.tar.gz ./bin ./resources
deploy:
  provider: releases
  api_key:
    secure: travis setup releases
  file: sorry-gen.tar.gz
  skip_cleanup: true
